### ISSUE TITLE
Activity?

### ISSUE THREAD

**Issue by halfdan** [DevDavido/AttackAlert#1]
Hi, are you still working on this plugin? I like the idea of integrating phpids into Piwik! Let me know if you need help in developing this plugin.

**Comment by DevDavido** [comment]
Hi there, currently I have no time for the next two months to work on this plugin. It would be great if you would contribute to this plugin or if you wish to, you could adopt it.

**Comment by halfdan** [comment]
@DevDavido, can you explain a little on what your plans with this plugin are? 

Should the plugin report attacks against Piwik or the websites tracked with Piwik?

**Comment by DevDavido** [comment]
@halfdan It should report attacks against the websites which are tracked by Piwik.

**Comment by halfdan** [comment]
The thing is that we don't have access to a lot of information required by PHPIDS.

Example from https://phpids.org/faq/

``` php
  use IDS\Init;
  use IDS\Monitor;
  require_once 'vendor/autoload.php';

  $request = array(
      'REQUEST' => $_REQUEST,
      'GET' => $_GET,
      'POST' => $_POST,
      'COOKIE' => $_COOKIE
  );

  $init = Init::init('path/to/Config.ini');
  $ids = new Monitor($request, $init);
  $result = $ids->run();

  if (!$result->isEmpty()) {
      // Take a look at the result object
      echo $result;
  }
```

We won't have access to $_POST and $_COOKIE of our tracked website.

**Comment by DevDavido** [comment]
Yes, you are right. Should we track then only the $_REQUEST/$_GET or have you an idea?

**Comment by halfdan** [comment]
I don't think that $_GET alone is all that interesting. Also consider that attackers probably won't use a browser with a activated JavaScript, which we rely on. 

Now there are other ways this plugin could work:
- Two part implementation:
  - Plugin for phpids that sends attack information to AttackAlert whenever phpids detects an attack
  - AttackAlert plugin records attacks and visualizes them (by attack type, occurence, etc.)
- Proxy
  - PHP-Script that is included on the tracked website and sends $_GET/$_POST/$_COOKIE to AttackAlerts via PiwikTracker.php

The last approach is not viable for bigger websites since it would trigger the same number of requests to the Piwik installation.

**Comment by DevDavido** [comment]
As you already mentioned would the last approach cause too high server load for big websites. We could rely on your first list point and make use of [auto_append_file](http://www.php.net/manual/en/ini.core.php#ini.auto-append-file)?
